---
# Source: nginx-gateway-fabric/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-gateway-fabric
  namespace: default
  labels:
    helm.sh/chart: nginx-gateway-fabric-1.5.1
    app.kubernetes.io/name: nginx-gateway-fabric
    app.kubernetes.io/instance: nginx-gateway-fabric
    app.kubernetes.io/version: "1.5.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    {}
---
# Source: nginx-gateway-fabric/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-includes-bootstrap
  namespace: default
  labels:
    helm.sh/chart: nginx-gateway-fabric-1.5.1
    app.kubernetes.io/name: nginx-gateway-fabric
    app.kubernetes.io/instance: nginx-gateway-fabric
    app.kubernetes.io/version: "1.5.1"
    app.kubernetes.io/managed-by: Helm
data:
  main.conf: |
    error_log stderr info;
---
# Source: nginx-gateway-fabric/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-gateway-fabric
  labels:
    helm.sh/chart: nginx-gateway-fabric-1.5.1
    app.kubernetes.io/name: nginx-gateway-fabric
    app.kubernetes.io/instance: nginx-gateway-fabric
    app.kubernetes.io/version: "1.5.1"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - services
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses
  - gateways
  - httproutes
  - referencegrants
  - grpcroutes
  verbs:
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes/status
  - gateways/status
  - gatewayclasses/status
  - grpcroutes/status
  verbs:
  - update
- apiGroups:
  - gateway.nginx.org
  resources:
  - nginxgateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.nginx.org
  resources:
  - nginxproxies
  - clientsettingspolicies
  - observabilitypolicies
  verbs:
  - list
  - watch
- apiGroups:
  - gateway.nginx.org
  resources:
  - nginxgateways/status
  - clientsettingspolicies/status
  - observabilitypolicies/status
  verbs:
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - watch
---
# Source: nginx-gateway-fabric/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nginx-gateway-fabric
  labels:
    helm.sh/chart: nginx-gateway-fabric-1.5.1
    app.kubernetes.io/name: nginx-gateway-fabric
    app.kubernetes.io/instance: nginx-gateway-fabric
    app.kubernetes.io/version: "1.5.1"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nginx-gateway-fabric
subjects:
- kind: ServiceAccount
  name: nginx-gateway-fabric
  namespace: default
---
# Source: nginx-gateway-fabric/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway-fabric
  namespace: default
  labels:
    helm.sh/chart: nginx-gateway-fabric-1.5.1
    app.kubernetes.io/name: nginx-gateway-fabric
    app.kubernetes.io/instance: nginx-gateway-fabric
    app.kubernetes.io/version: "1.5.1"
    app.kubernetes.io/managed-by: Helm
spec:
  externalTrafficPolicy: Local
  type: NodePort
  selector:
    app.kubernetes.io/name: nginx-gateway-fabric
    app.kubernetes.io/instance: nginx-gateway-fabric
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
---
# Source: nginx-gateway-fabric/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gateway-fabric
  namespace: default
  labels:
    helm.sh/chart: nginx-gateway-fabric-1.5.1
    app.kubernetes.io/name: nginx-gateway-fabric
    app.kubernetes.io/instance: nginx-gateway-fabric
    app.kubernetes.io/version: "1.5.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-gateway-fabric
      app.kubernetes.io/instance: nginx-gateway-fabric
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-gateway-fabric
        app.kubernetes.io/instance: nginx-gateway-fabric
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
    spec:
      initContainers:
      - name: init
        image: ghcr.io/nginxinc/nginx-gateway-fabric:1.5.1
        imagePullPolicy: IfNotPresent
        command:
        - /usr/bin/gateway
        - initialize
        - --source
        - /includes/main.conf
        - --destination
        - /etc/nginx/main-includes
        env:
          - name: POD_UID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            add:
            - KILL # Set because the binary has CAP_KILL for the main controller process. Not used by init.
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsUser: 102
          runAsGroup: 1001
        volumeMounts:
        - name: nginx-includes-bootstrap
          mountPath: /includes
        - name: nginx-main-includes
          mountPath: /etc/nginx/main-includes
      containers:
      - args:
        - static-mode
        - --gateway-ctlr-name=gateway.nginx.org/nginx-gateway-controller
        - --gatewayclass=nginx-gateway-class
        - --config=nginx-gateway-fabric-config
        - --service=nginx-gateway-fabric
        - --metrics-port=9113
        - --health-port=8081
        - --leader-election-lock-name=nginx-gateway-fabric-leader-election
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        image: ghcr.io/nginxinc/nginx-gateway-fabric:1.5.1
        imagePullPolicy: IfNotPresent
        name: nginx-gateway
        ports:
        - name: metrics
          containerPort: 9113
        - name: health
          containerPort: 8081
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 3
          periodSeconds: 1
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - KILL
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsUser: 102
          runAsGroup: 1001
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
        - name: nginx-stream-conf
          mountPath: /etc/nginx/stream-conf.d
        - name: nginx-main-includes
          mountPath: /etc/nginx/main-includes
        - name: nginx-secrets
          mountPath: /etc/nginx/secrets
        - name: nginx-run
          mountPath: /var/run/nginx
        - name: nginx-includes
          mountPath: /etc/nginx/includes
      - image: ghcr.io/nginxinc/nginx-gateway-fabric/nginx:1.5.1
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsUser: 101
          runAsGroup: 1001
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
        - name: nginx-stream-conf
          mountPath: /etc/nginx/stream-conf.d
        - name: nginx-main-includes
          mountPath: /etc/nginx/main-includes
        - name: nginx-secrets
          mountPath: /etc/nginx/secrets
        - name: nginx-run
          mountPath: /var/run/nginx
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-includes
          mountPath: /etc/nginx/includes
      terminationGracePeriodSeconds: 30
      serviceAccountName: nginx-gateway-fabric
      shareProcessNamespace: true
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
      volumes:
      - name: nginx-conf
        emptyDir: {}
      - name: nginx-stream-conf
        emptyDir: {}
      - name: nginx-main-includes
        emptyDir: {}
      - name: nginx-secrets
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-includes
        emptyDir: {}
      - name: nginx-includes-bootstrap
        configMap:
          name: nginx-includes-bootstrap
---
# Source: nginx-gateway-fabric/templates/nginxgateway.yaml
apiVersion: gateway.nginx.org/v1alpha1
kind: NginxGateway
metadata:
  name: nginx-gateway-fabric-config
  namespace: default
  labels:
    helm.sh/chart: nginx-gateway-fabric-1.5.1
    app.kubernetes.io/name: nginx-gateway-fabric
    app.kubernetes.io/instance: nginx-gateway-fabric
    app.kubernetes.io/version: "1.5.1"
    app.kubernetes.io/managed-by: Helm
spec:
  logging:
    level: info
